### PR TITLE
Enable cacheFile option in gatsby-plugin-jsxstyle

### PR DESCRIPTION
**Pull request by aamorozov**
This solves the issue with jsxstyle generated classname properties not being compiled on initial page load in production build.

### CODE REVIEW

**Comment by aamorozov** [comment]
@meyer That worked for me - added changes to the pr

**Comment by meyer** [comment]
Once I’ve got CI fixed I’ll land this PR and publish a new release.

**Comment by meyer** [comment]
@aamorozov published as `gatsby-plugin-jsxstyle@0.0.4`

**Comment by aamorozov** [comment]
Awesome, thank you @meyer !

**Pull request merged**
