### PR TITLE
Add pattern for Windows paths in loader schema

### PR DESCRIPTION
**Pull request by chenxsan**
The original pattern will cause error on Windows OS, this pull request should fix it.

### CODE REVIEW

**Comment by chenxsan** [comment]
@meyer Sorry for late response! Yes, I've tested it on my Windows 10. Here's how those directories look on my Windows 10 when I add `console.table(options)` here https://github.com/jsxstyle/jsxstyle/blob/master/packages/jsxstyle-webpack-plugin/src/utils/ast/extractStyles.ts#L162:

IMG_7191

I don't think the regexp will cover all Windows' path cases, but at least it works in my case.

**Comment by meyer** [comment]
@chenxsan rad, thanks for the followup! I’ll land this now. If more Windows folks have issues we can revisit this.

**Comment by chenxsan** [comment]
@meyer Hi, any plan to release a new version? [My project](https://github.com/OkMarvin/january) counts on it to build on windows :)

**Comment by meyer** [comment]
@chenxsan thanks for the nudge! I just published `jsxstyle-webpack-plugin@1.1.6` which includes this change.

**Pull request merged**
